"use strict";var Core=Core||{};Core.Customer=Core.Customer||{};Core.Customer.TicketMessage=(function(TargetNS){TargetNS.Init=function(){var $Form,FieldID,DynamicFieldNames=Core.Config.Get('DynamicFieldNames'),Fields=['TypeID','Dest','PriorityID','ServiceID','SLAID'],ModifiedFields;$.each(Fields,function(Index,Value){ModifiedFields=Core.Data.CopyObject(Fields).concat(DynamicFieldNames);ModifiedFields.splice(Index,1);FieldUpdate(Value,ModifiedFields);});$('button[id*=AttachmentDeleteButton]').on('click',function(){$Form=$(this).closest('form');FieldID=$(this).attr('id').split('AttachmentDeleteButton')[1];$('#AttachmentDelete'+FieldID).val(1);Core.Form.Validate.DisableValidation($Form);$Form.trigger('submit');});};function FieldUpdate(Value,ModifiedFields){$('#'+Value).on('change',function(){Core.AJAX.FormUpdate($('#NewCustomerTicket'),'AJAXUpdate',Value,ModifiedFields);});}
Core.Init.RegisterNamespace(TargetNS,'APP_MODULE');return TargetNS;}(Core.Customer.TicketMessage||{}));

"use strict";var Core=Core||{};Core.Agent=Core.Agent||{};Core.Agent.DynamicFieldByServicePreLoad={};Core.Agent.DynamicFieldByServiceLastFocus=null;Core.Agent.DynamicFieldByServiceLastChangedElement=null;Core.Agent.DynamicFieldByServiceLastKey=null;Core.Agent.ClearFormIfEmptyConfig=null;Core.Agent.checkLigeroForms;Core.Agent.DynamicFieldByService=(function(TargetNS){TargetNS.Init=function(){var arrayJSON;var objectJSON;var reloadFields="";var uploadFields={};$('#ServiceID').trigger("change");var checkLigeroForms=function(webAction){return function(){if($('#ServiceID').val()){$('.InputField_Search').attr("aria-expanded","true");var formID="";$("form").each(function(){if($(this).attr("name")=="compose"){formID=$(this).attr("id");}});var Data={Action:'DynamicFieldByService',OriginalAction:Core.Config.Get('Action'),Subaction:webAction,ServiceDynamicID:$('#ServiceID').val(),InterfaceName:formID,IsAjaxRequest:1,IsMainWindow:1};if(!Core.Config.Get('SessionIDCookie')){Data[Core.Config.Get('SessionName')]=Core.Config.Get('SessionID');Data[Core.Config.Get('CustomerPanelSessionName')]=Core.Config.Get('SessionID');}
Data.ChallengeToken=Core.Config.Get('ChallengeToken');if(webAction=='HideAndShowDynamicFields'){var QueryString='';$.each(Data,function(Key,Value){QueryString+=';'+encodeURIComponent(Key)+'='+encodeURIComponent(Value);});Data=Core.AJAX.SerializeForm($('#'+formID),Data)+QueryString;}
Core.AJAX.FunctionCall(Core.Config.Get('CGIHandle'),Data,function(Response){if(Response==0){if(Core.Agent.ClearFormIfEmptyConfig==1)
cleanOldLigeroFormFields();Core.UI.InputFields.Deactivate();Core.UI.InputFields.Activate();return;}
try{$(Response).find('.AddDFS').each(function(){var dfsID=$(this).attr('id');$('#'+dfsID).not('.AddDFS').each(function(){Core.Agent.DynamicFieldByServicePreLoad[dfsID]={value:$(this).val(),attr:$(this).attr('class')};$(this).parent().parent().remove();});});}catch(e){}
Core.Agent.DynamicFieldByServicePreLoad['Message']={value:$('#RichText').val()};$('.AddDFS').each(function(){var $that=$(this);if($that.is(':file'))
uploadFields[$that.attr('id')]=$that.clone();});var res=Response.split(':$$:Add:$$:');Response=res[0];arrayJSON=res[1].split('@%@%@');var i;reloadFields="";var AgentFieldConfigInsert=".SpacingTop:first";var CustomerFieldConfigInsert="#BottomActionRow";for(i=0;i<arrayJSON.length;i++){objectJSON=$.parseJSON(arrayJSON[i]);$.each(objectJSON,function(key,val){if(key&&val){if(key==="Message"&&val.trim().length){window.CKEDITOR.instances['RichText'].on('instanceReady',function(){window.CKEDITOR.instances['RichText'].setData(val);});window.CKEDITOR.instances['RichText'].setData(val);reloadFields+=""+key+",";}else if(key==="HideArticle"&&val==='1'&&Core.Config.Get('Action').search(/^Customer/)>-1){$('#Subject').parent().hide();$('.RichTextHolder').hide();$('.DnDUploadBox').parent().parent().hide();}else if(key==="AgentFieldConfig"){AgentFieldConfigInsert=""+val+"";}else if($('#'+key).length>0){reloadFields+=""+key+",";$('#'+key).val(val);}
if(key==='ClearFormIfEmptyConfig'&&Core.Agent.ClearFormIfEmptyConfig===null){Core.Agent.ClearFormIfEmptyConfig=parseInt(val);}
if(key==="CustomerFieldConfig"){CustomerFieldConfigInsert=""+val+"";}}});}
reloadFields=reloadFields.substring(0,reloadFields.length-1);var FieldConfigInsert="";if(formID==="NewCustomerTicket"){FieldConfigInsert=CustomerFieldConfigInsert;}
else{FieldConfigInsert=AgentFieldConfigInsert;}
cleanOldLigeroFormFields();var $ElementToUpdate=$(Response).insertBefore(FieldConfigInsert);Object.keys(uploadFields).forEach(function(i,v){$("#"+i).replaceWith(uploadFields[i]);});Core.UI.InputFields.Deactivate();Core.UI.InputFields.Activate();var JavaScriptString='';var ErrorMessage;if($ElementToUpdate&&isJQueryObject($ElementToUpdate)&&$ElementToUpdate.length){$ElementToUpdate.find('script').each(function(){JavaScriptString+=$(this).html();$(this).remove();});try{eval(JavaScriptString);}catch(Event){$.noop(Event);}
if($ElementToUpdate.children().first().hasClass('ServerError')){ErrorMessage=$ElementToUpdate.children().first().data('message');$('#ServiceID').addClass('ServerError');$('#ProcessEntityIDServerError').children().first().text(ErrorMessage);}
Core.Form.Validate.Init();Core.UI.TreeSelection.InitTreeSelection();$('.Row > .FieldHelpContainer').each(function(){if(!$(this).next('label').find('.Marker').length){$(this).prependTo($(this).next('label'));}else{$(this).insertAfter($(this).next('label').find('.Marker'));}});Core.UI.TreeSelection.InitDynamicFieldTreeViewRestore();if(Core.App.Responsive.IsSmallerOrEqual(Core.App.Responsive.GetScreenSize(),'ScreenL'))
Core.App.Publish('Event.App.Responsive.SmallerOrEqualScreenL');jQuery.each(Core.Agent.DynamicFieldByServicePreLoad,function(oKey,oObj){if(oKey=='Message'&&oObj.value.length){window.CKEDITOR.instances['RichText'].on('instanceReady',function(){window.CKEDITOR.instances['RichText'].setData(oObj.value);});window.CKEDITOR.instances['RichText'].setData(oObj.value);}else{$('#'+oKey).val(oObj.value).attr('class',oObj.attr);}});Core.Agent.DynamicFieldByServicePreLoad={};$(".AddDFS").not('.RemoveDFS').each(function(){if($(this).hasClass('DateSelection')||$(this).hasClass('Validate_MaxLength'))
return true;var formID="";$("form").each(function(){if($(this).attr("name")=="compose"){formID=$(this).attr("id");}});var $inputs=$('#'+formID+' :input');var ids=[];$inputs.each(function(index){if(typeof $(this).attr('id')!='undefined'&&typeof $(this).attr('name')!='undefined'){ids.push($(this).attr('id'));}});var index=ids.indexOf('FileUpload');if(index!==-1)ids.splice(index,1);var id=$(this).attr('id');$("#"+id).bind('change',function(e){Core.Agent.DynamicFieldByServiceLastChangedElement=id;});});}else{$('#AJAXLoader').addClass('Hidden');}
$("[id^='DynamicField_'][data-ligeroform!='ok']:not(.InputField_Search)").each(function(){$(this)
.bind('change',checkLigeroForms('HideAndShowDynamicFields'))});$("[id^='DynamicField_'][data-ligeroform!='ok']").each(function(){$(this)
.bind('focus.jstree',storeLigeroFormLastFocus)
.attr('data-ligeroform','ok');});},'html');}else{cleanOldLigeroFormFields();if(reloadFields.length){var arrayFieldsClean=reloadFields.split(',');var i;for(i=0;i<arrayFieldsClean.length;i++){if(arrayFieldsClean[i]==="Message"){window.CKEDITOR.instances['RichText'].setData('');}else if($('#'+arrayFieldsClean[i]).length>0){$('#'+arrayFieldsClean[i]).val('');}}
Core.AJAX.FormUpdate($('#'+formID),'AJAXUpdate','ServiceID',[reloadFields]);$('#Subject').parent().show();$('.RichTextHolder').show();$('.DnDUploadBox').parent().parent().show();$('#AJAXLoaderSubject\\,Message').hide();}}
return false;};};var cleanOldLigeroFormFields=function(){$('.AddDFS').each(function(){var $that=$(this);$that.parents('.Row').remove();}).addClass('RemoveDFS');if(Core.Agent.ClearFormIfEmptyConfig==1)
window.CKEDITOR.instances['RichText'].setData('');};var storeLigeroFormLastFocus=function(e){if(typeof e!=='undefined'&&typeof e.target.id!=='undefined'){var ModernizeSubelement=/_anchor$/;var NewFocus=''
if(ModernizeSubelement.test(e.target.id)){NewFocus=$('#'+e.target.id).parent().parent().parent().attr('id');NewFocus=NewFocus.replace('_Select','_Search');}else{NewFocus=e.target.id}
Core.Agent.DynamicFieldByServiceLastFocus=NewFocus;}};var restoreLastFocus=function(e){if(Core.Agent.DynamicFieldByServiceLastFocus!==null){$('.jstree').parent().parent().remove();console.log('olha ai '+Core.Agent.DynamicFieldByServiceLastFocus);var setFocus=function(element){$('#'+element).focus();}
setTimeout(setFocus(Core.Agent.DynamicFieldByServiceLastFocus),400);}
}
var restoreLastFocusFromCallBack=function(id){if(Core.Agent.DynamicFieldByServiceLastFocus!==null&&Core.Agent.DynamicFieldByServiceLastFocus.replace('_Search','').replace('_Select','')==id){setTimeout(restoreLastFocus(),0);}}
var FormsKey=function(Event){if(typeof Event!=='undefined'&&Event.which===$.ui.keyCode.TAB){Core.Agent.DynamicFieldByServiceLastKey='TAB';}else{Core.Agent.DynamicFieldByServiceLastKey='';}
storeLigeroFormLastFocus(Event);};document.addEventListener('keyup',FormsKey,true);document.addEventListener('keydown',FormsKey,true);document.addEventListener('keydpress',FormsKey,true);$("#ServiceID[data-ligeroform!='ok']").each(function(){$(this)
.bind('change',checkLigeroForms('DisplayActivityDialogAJAX'))
.bind('focus',storeLigeroFormLastFocus)
.attr('data-ligeroform','ok');});$("#ServiceID").on('change',()=>{cleanOldLigeroFormFields();checkLigeroForms('DisplayActivityDialogAJAX');})};Core.Init.RegisterNamespace(TargetNS,'APP_MODULE_LATE');return TargetNS;}(Core.Agent.DynamicFieldByService||{}));

